[04/Aug/2021 10:00:22,949] [31m[0m
[04/Aug/2021 10:00:22,949] [31mRequest on POST /mobile/user/login ended with code: 400[0m
[04/Aug/2021 10:00:22,949] [31mUser: Anonymous User[0m
[04/Aug/2021 10:00:22,949] [31mRequest details:[0m
[04/Aug/2021 10:00:22,950] [31m{'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '286ad30c-5bd6-4c0a-9f97-e250060096d1', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[04/Aug/2021 10:00:22,950] [31mResponse details:[0m
[04/Aug/2021 10:00:22,950] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Cookie, Origin'), 'allow': ('Allow', 'POST, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '41')}[0m
[04/Aug/2021 10:00:22,951] [31m{"message":"Incorrect email or password"}[0m
[04/Aug/2021 10:00:22,951] [31mUsed tables: django_session, users_user[0m
[04/Aug/2021 10:00:35,590] [32m[0m
[04/Aug/2021 10:00:35,590] [32mRequest on POST /mobile/user/login ended with code: 200[0m
[04/Aug/2021 10:00:35,590] [32mUser: Anonymous User[0m
[04/Aug/2021 10:00:35,590] [32mUsed tables: django_session, users_user, users_account[0m
[04/Aug/2021 10:08:14,580] [31m[0m
[04/Aug/2021 10:08:14,581] [31mRequest on GET / ended with code: 404[0m
[04/Aug/2021 10:08:14,581] [31mUser: Anonymous User[0m
[04/Aug/2021 10:08:14,581] [31mRequest details:[0m
[04/Aug/2021 10:08:14,581] [31m{'HTTP_HOST': '127.0.0.1:8000', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_SEC_CH_UA': '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"', 'HTTP_SEC_CH_UA_MOBILE': '?0', 'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36', 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 'HTTP_SEC_FETCH_SITE': 'none', 'HTTP_SEC_FETCH_MODE': 'navigate', 'HTTP_SEC_FETCH_USER': '?1', 'HTTP_SEC_FETCH_DEST': 'document', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9'}[0m
[04/Aug/2021 10:08:14,581] [31mResponse details:[0m
[04/Aug/2021 10:08:14,581] [31m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[04/Aug/2021 10:08:14,582] [31m{"status_code": 404, "message": "Not found"}[0m
[04/Aug/2021 10:08:14,661] [31m[0m
[04/Aug/2021 10:08:14,661] [31mRequest on GET /favicon.ico ended with code: 404[0m
[04/Aug/2021 10:08:14,661] [31mUser: Anonymous User[0m
[04/Aug/2021 10:08:14,661] [31mRequest details:[0m
[04/Aug/2021 10:08:14,662] [31m{'HTTP_HOST': '127.0.0.1:8000', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_SEC_CH_UA': '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"', 'HTTP_SEC_CH_UA_MOBILE': '?0', 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36', 'HTTP_ACCEPT': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8', 'HTTP_SEC_FETCH_SITE': 'same-origin', 'HTTP_SEC_FETCH_MODE': 'no-cors', 'HTTP_SEC_FETCH_DEST': 'image', 'HTTP_REFERER': 'http://127.0.0.1:8000/', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.9'}[0m
[04/Aug/2021 10:08:14,662] [31mResponse details:[0m
[04/Aug/2021 10:08:14,662] [31m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[04/Aug/2021 10:08:14,662] [31m{"status_code": 404, "message": "Not found"}[0m
[04/Aug/2021 10:50:03,077] [32m[0m
[04/Aug/2021 10:50:03,078] [32mRequest on POST /mobile/user/login ended with code: 200[0m
[04/Aug/2021 10:50:03,078] [32mUser: Anonymous User[0m
[04/Aug/2021 10:50:03,079] [32mUsed tables: django_session, users_account, users_user[0m
[04/Aug/2021 10:50:16,702] [31m[0m
[04/Aug/2021 10:50:16,703] [31mRequest on GET /admin/table ended with code: 401[0m
[04/Aug/2021 10:50:16,703] [31mUser: Anonymous User[0m
[04/Aug/2021 10:50:16,703] [31mRequest details:[0m
[04/Aug/2021 10:50:16,704] [31m{'HTTP_LANGUAGE': 'ru', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '195fc80d-314f-42fc-8d9d-237bf83076f2', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=ow03pou9qtv48555xlo51a3l4t2kpn1w'}[0m
[04/Aug/2021 10:50:16,705] [31m{[0m
[04/Aug/2021 10:50:16,705] [31m    "office_id": "1420b7a7-c3da-4042-9902-226ab753aeff",[0m
[04/Aug/2021 10:50:16,705] [31m    "date": "2021-7-6"[0m
[04/Aug/2021 10:50:16,705] [31m}[0m
[04/Aug/2021 10:50:16,705] [31mResponse details:[0m
[04/Aug/2021 10:50:16,705] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'www-authenticate': ('WWW-Authenticate', 'Bearer realm="api"'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '58')}[0m
[04/Aug/2021 10:50:16,706] [31m{"detail":"Authentication credentials were not provided."}[0m
[04/Aug/2021 10:50:26,209] [35;1m[35;1mInternal Server Error: /admin/table[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 10:50:26,217] [31m[0m
[04/Aug/2021 10:50:26,218] [31mRequest on GET /admin/table ended with code: 500[0m
[04/Aug/2021 10:50:26,265] [31mUser: Anonymous User[0m
[04/Aug/2021 10:50:26,265] [31mRequest details:[0m
[04/Aug/2021 10:50:26,266] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_LANGUAGE': 'ru', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '0ca32294-caa0-4f23-9cfa-318f036b90aa', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=ow03pou9qtv48555xlo51a3l4t2kpn1w'}[0m
[04/Aug/2021 10:50:26,266] [31m{[0m
[04/Aug/2021 10:50:26,266] [31m    "office_id": "1420b7a7-c3da-4042-9902-226ab753aeff",[0m
[04/Aug/2021 10:50:26,267] [31m    "date": "2021-7-6"[0m
[04/Aug/2021 10:50:26,267] [31m}[0m
[04/Aug/2021 10:50:26,268] [31mResponse details:[0m
[04/Aug/2021 10:50:26,268] [31mUsed tables: django_session[0m
[04/Aug/2021 10:51:11,465] [35;1m[35;1mInternal Server Error: /admin/table[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 10:51:11,466] [31m[0m
[04/Aug/2021 10:51:11,466] [31mRequest on GET /admin/table ended with code: 500[0m
[04/Aug/2021 10:51:11,506] [31mUser: Anonymous User[0m
[04/Aug/2021 10:51:11,506] [31mRequest details:[0m
[04/Aug/2021 10:51:11,506] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_LANGUAGE': 'ru', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'e131c5ce-e4fd-4072-9060-a60a07736294', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=ow03pou9qtv48555xlo51a3l4t2kpn1w'}[0m
[04/Aug/2021 10:51:11,506] [31mResponse details:[0m
[04/Aug/2021 10:51:11,507] [31mUsed tables: django_session[0m
[04/Aug/2021 10:51:48,698] [35;1m[35;1mInternal Server Error: /admin/table[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 10:51:48,700] [31m[0m
[04/Aug/2021 10:51:48,700] [31mRequest on GET /admin/table ended with code: 500[0m
[04/Aug/2021 10:51:48,748] [31mUser: Anonymous User[0m
[04/Aug/2021 10:51:48,748] [31mRequest details:[0m
[04/Aug/2021 10:51:48,749] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_LANGUAGE': 'ru', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '2e391669-9512-483c-b225-8e501c2f690b', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=ow03pou9qtv48555xlo51a3l4t2kpn1w'}[0m
[04/Aug/2021 10:51:48,749] [31mResponse details:[0m
[04/Aug/2021 10:51:48,750] [31mUsed tables: django_session[0m
[04/Aug/2021 10:52:56,889] [35;1m[35;1mInternal Server Error: /admin/user[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 10:52:56,889] [31m[0m
[04/Aug/2021 10:52:56,890] [31mRequest on GET /admin/user ended with code: 500[0m
[04/Aug/2021 10:52:56,936] [31mUser: Anonymous User[0m
[04/Aug/2021 10:52:56,937] [31mRequest details:[0m
[04/Aug/2021 10:52:56,937] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_LANGUAGE': 'ru', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '84c3ab0b-93af-4c51-a25b-1617a7be7755', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=ow03pou9qtv48555xlo51a3l4t2kpn1w'}[0m
[04/Aug/2021 10:52:56,938] [31mResponse details:[0m
[04/Aug/2021 10:52:56,938] [31mUsed tables: django_session[0m
[04/Aug/2021 10:56:56,938] [35;1m[35;1mInternal Server Error: /admin/user[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 10:56:56,941] [31m[0m
[04/Aug/2021 10:56:56,941] [31mRequest on GET /admin/user ended with code: 500[0m
[04/Aug/2021 10:56:56,979] [31mUser: Anonymous User[0m
[04/Aug/2021 10:56:56,979] [31mRequest details:[0m
[04/Aug/2021 10:56:56,980] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_LANGUAGE': 'ru', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'a508cccd-990b-48b1-8ced-80b9c45c3a91', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=ow03pou9qtv48555xlo51a3l4t2kpn1w'}[0m
[04/Aug/2021 10:56:56,980] [31mResponse details:[0m
[04/Aug/2021 10:56:56,980] [31mUsed tables: django_session[0m
[04/Aug/2021 10:57:24,653] [35;1m[35;1mInternal Server Error: /admin/user[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 10:57:24,653] [31m[0m
[04/Aug/2021 10:57:24,654] [31mRequest on GET /admin/user ended with code: 500[0m
[04/Aug/2021 10:57:24,688] [31mUser: Anonymous User[0m
[04/Aug/2021 10:57:24,688] [31mRequest details:[0m
[04/Aug/2021 10:57:24,689] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_LANGUAGE': 'ru', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '3e8ced91-4f48-4980-9e6c-463bbefa646a', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_COOKIE': 'sessionid=ow03pou9qtv48555xlo51a3l4t2kpn1w'}[0m
[04/Aug/2021 10:57:24,690] [31mResponse details:[0m
[04/Aug/2021 10:57:24,690] [31mUsed tables: django_session[0m
[04/Aug/2021 10:57:34,079] [35;1m[35;1mInternal Server Error: /admin/user[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 10:57:34,080] [31m[0m
[04/Aug/2021 10:57:34,081] [31mRequest on GET /admin/user ended with code: 500[0m
[04/Aug/2021 10:57:34,121] [31mUser: Anonymous User[0m
[04/Aug/2021 10:57:34,121] [31mRequest details:[0m
[04/Aug/2021 10:57:34,121] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '28881576-7863-4eed-9967-c198c35d0756', 'HTTP_COOKIE': 'sessionid=ow03pou9qtv48555xlo51a3l4t2kpn1w'}[0m
[04/Aug/2021 10:57:34,121] [31mResponse details:[0m
[04/Aug/2021 10:57:34,122] [31mUsed tables: django_session[0m
[04/Aug/2021 10:58:56,235] [35;1m[35;1mInternal Server Error: /admin/user[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 10:58:56,236] [31m[0m
[04/Aug/2021 10:58:56,236] [31mRequest on GET /admin/user ended with code: 500[0m
[04/Aug/2021 10:58:56,296] [31mUser: Anonymous User[0m
[04/Aug/2021 10:58:56,296] [31mRequest details:[0m
[04/Aug/2021 10:58:56,297] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'c7cd01b2-a740-4607-a9b8-01d4b7548241', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=ow03pou9qtv48555xlo51a3l4t2kpn1w'}[0m
[04/Aug/2021 10:58:56,297] [31mResponse details:[0m
[04/Aug/2021 10:58:56,297] [31mUsed tables: django_session[0m
[04/Aug/2021 10:59:55,086] [32m[0m
[04/Aug/2021 10:59:55,086] [32mRequest on POST /mobile/user/login ended with code: 200[0m
[04/Aug/2021 10:59:55,086] [32mUser: Anonymous User[0m
[04/Aug/2021 10:59:55,087] [32mUsed tables: django_session, users_user, users_account[0m
[04/Aug/2021 11:00:00,545] [35;1m[35;1mInternal Server Error: /admin/user[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 11:00:00,547] [31m[0m
[04/Aug/2021 11:00:00,547] [31mRequest on POST /admin/user ended with code: 500[0m
[04/Aug/2021 11:00:00,583] [31mUser: Anonymous User[0m
[04/Aug/2021 11:00:00,583] [31mRequest details:[0m
[04/Aug/2021 11:00:00,584] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '4fc45a2f-bb32-42ec-81e0-0a11b6dd153d', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=0anwjcra7qpucu0jznr4i4k9a577z4zv'}[0m
[04/Aug/2021 11:00:00,584] [31mResponse details:[0m
[04/Aug/2021 11:00:00,585] [31mUsed tables: django_session[0m
[04/Aug/2021 11:01:19,588] [32m[0m
[04/Aug/2021 11:01:19,588] [32mRequest on POST /mobile/user/login ended with code: 200[0m
[04/Aug/2021 11:01:19,588] [32mUser: Anonymous User[0m
[04/Aug/2021 11:01:19,588] [32mUsed tables: django_session, users_user, users_account[0m
[04/Aug/2021 11:01:29,603] [35;1m[35;1mInternal Server Error: /admin/user[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 11:01:29,604] [31m[0m
[04/Aug/2021 11:01:29,604] [31mRequest on GET /admin/user ended with code: 500[0m
[04/Aug/2021 11:01:29,640] [31mUser: Anonymous User[0m
[04/Aug/2021 11:01:29,640] [31mRequest details:[0m
[04/Aug/2021 11:01:29,640] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'f5ff0bff-92e4-403a-bc5a-4f711937ef70', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=0anwjcra7qpucu0jznr4i4k9a577z4zv'}[0m
[04/Aug/2021 11:01:29,640] [31mResponse details:[0m
[04/Aug/2021 11:01:29,640] [31mUsed tables: django_session[0m
[04/Aug/2021 11:03:08,152] [35;1m[35;1mInternal Server Error: /admin/user[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 11:03:08,155] [31m[0m
[04/Aug/2021 11:03:08,155] [31mRequest on GET /admin/user ended with code: 500[0m
[04/Aug/2021 11:03:08,157] [31mUser: Anonymous User[0m
[04/Aug/2021 11:03:08,157] [31mRequest details:[0m
[04/Aug/2021 11:03:08,157] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '180fdb10-be29-4bf7-9a33-ce612fe73ff4', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=0anwjcra7qpucu0jznr4i4k9a577z4zv'}[0m
[04/Aug/2021 11:03:08,158] [31mResponse details:[0m
[04/Aug/2021 11:05:58,431] [35;1m[35;1mInternal Server Error: /book[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 11:05:58,436] [31m[0m
[04/Aug/2021 11:05:58,437] [31mRequest on GET /book ended with code: 500[0m
[04/Aug/2021 11:05:58,472] [31mUser: Anonymous User[0m
[04/Aug/2021 11:05:58,472] [31mRequest details:[0m
[04/Aug/2021 11:05:58,473] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '1c7e6cac-848c-4e3b-bc84-c6af4b508aaa', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=0anwjcra7qpucu0jznr4i4k9a577z4zv'}[0m
[04/Aug/2021 11:05:58,473] [31mResponse details:[0m
[04/Aug/2021 11:05:58,473] [31mUsed tables: django_session[0m
[04/Aug/2021 11:09:30,644] [35;1m[35;1mInternal Server Error: /admin/user[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 11:09:48,395] [35;1m[35;1mInternal Server Error: /admin/user[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 11:10:02,312] [35;1m[35;1mInternal Server Error: /admin/user[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 11:10:02,315] [31m[0m
[04/Aug/2021 11:10:02,316] [31mRequest on GET /admin/user ended with code: 500[0m
[04/Aug/2021 11:10:02,316] [31mUser: Anonymous User[0m
[04/Aug/2021 11:10:02,316] [31mRequest details:[0m
[04/Aug/2021 11:10:02,316] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'c87b497f-8c07-42bb-ba7d-83744bbaf98f', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=0anwjcra7qpucu0jznr4i4k9a577z4zv'}[0m
[04/Aug/2021 11:10:02,316] [31mResponse details:[0m
[04/Aug/2021 11:20:00,448] [32m[0m
[04/Aug/2021 11:20:00,449] [32mRequest on POST /mobile/user/login ended with code: 200[0m
[04/Aug/2021 11:20:00,449] [32mUser: Anonymous User[0m
[04/Aug/2021 11:20:00,451] [32mUsed tables: users_account, django_session, users_user[0m
[04/Aug/2021 11:20:03,685] [35;1m[35;1mInternal Server Error: /admin/user[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'fe87620c-5e80-4a1c-9c30-c4681387483a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 37, in authenticate
    return self.get_user(validated_token), validated_token
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework_simplejwt/authentication.py", line 110, in get_user
    user = User.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'fe87620c-5e80-4a1c-9c30-c4681387483a'.
[04/Aug/2021 11:20:03,688] [31m[0m
[04/Aug/2021 11:20:03,688] [31mRequest on GET /admin/user ended with code: 500[0m
[04/Aug/2021 11:20:03,688] [31mUser: Anonymous User[0m
[04/Aug/2021 11:20:03,688] [31mRequest details:[0m
[04/Aug/2021 11:20:03,688] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'b2cf2d7a-5024-4711-a012-a4343ea4d143', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=vbl4zxe25pn33x7v5176ek3hm6hcaqsr'}[0m
[04/Aug/2021 11:20:03,688] [31mResponse details:[0m
[04/Aug/2021 11:49:14,675] [32m[0m
[04/Aug/2021 11:49:14,676] [32mRequest on POST /mobile/user/login ended with code: 200[0m
[04/Aug/2021 11:49:14,676] [32mUser: Anonymous User[0m
[04/Aug/2021 11:49:14,676] [32mUsed tables: django_session, users_account, users_user[0m
[04/Aug/2021 11:49:19,813] [31m[0m
[04/Aug/2021 11:49:19,813] [31mRequest on POST /admin/user ended with code: 403[0m
[04/Aug/2021 11:49:19,813] [31mUser: Anonymous User[0m
[04/Aug/2021 11:49:19,813] [31mRequest details:[0m
[04/Aug/2021 11:49:19,814] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '7253eab3-75d1-4013-8cec-212b88637152', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=l8jjeu8z19hx1jfkjehn8wwiur4mgelw'}[0m
[04/Aug/2021 11:49:19,814] [31mResponse details:[0m
[04/Aug/2021 11:49:19,815] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Cookie, Origin'), 'allow': ('Allow', 'GET, POST, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '58')}[0m
[04/Aug/2021 11:49:19,815] [31m{"detail":"Authentication credentials were not provided."}[0m
[04/Aug/2021 11:49:19,815] [31mUsed tables: django_session[0m
[04/Aug/2021 11:49:23,163] [31m[0m
[04/Aug/2021 11:49:23,163] [31mRequest on GET /admin/user ended with code: 403[0m
[04/Aug/2021 11:49:23,163] [31mUser: Anonymous User[0m
[04/Aug/2021 11:49:23,163] [31mRequest details:[0m
[04/Aug/2021 11:49:23,164] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '0030bc3a-9ade-46d0-aa09-88a7557875df', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=l8jjeu8z19hx1jfkjehn8wwiur4mgelw'}[0m
[04/Aug/2021 11:49:23,165] [31mResponse details:[0m
[04/Aug/2021 11:49:23,165] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Cookie, Origin'), 'allow': ('Allow', 'GET, POST, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '58')}[0m
[04/Aug/2021 11:49:23,165] [31m{"detail":"Authentication credentials were not provided."}[0m
[04/Aug/2021 11:49:23,165] [31mUsed tables: django_session[0m
[04/Aug/2021 11:49:45,838] [31m[0m
[04/Aug/2021 11:49:45,839] [31mRequest on POST /admin/user ended with code: 403[0m
[04/Aug/2021 11:49:45,839] [31mUser: Anonymous User[0m
[04/Aug/2021 11:49:45,839] [31mRequest details:[0m
[04/Aug/2021 11:49:45,839] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '98aac70c-c4bf-4ee3-b3f9-d8f2daca853a', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=l8jjeu8z19hx1jfkjehn8wwiur4mgelw'}[0m
[04/Aug/2021 11:49:45,840] [31m{[0m
[04/Aug/2021 11:49:45,840] [31m    "email": "chpi@liis.su",[0m
[04/Aug/2021 11:49:45,840] [31m    "phone_number": "89118777872"[0m
[04/Aug/2021 11:49:45,840] [31m}[0m
[04/Aug/2021 11:49:45,840] [31m[0m
[04/Aug/2021 11:49:45,841] [31mResponse details:[0m
[04/Aug/2021 11:49:45,841] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Cookie, Origin'), 'allow': ('Allow', 'GET, POST, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '58')}[0m
[04/Aug/2021 11:49:45,842] [31m{"detail":"Authentication credentials were not provided."}[0m
[04/Aug/2021 11:49:45,842] [31mUsed tables: django_session[0m
[04/Aug/2021 11:49:50,907] [31m[0m
[04/Aug/2021 11:49:50,907] [31mRequest on POST /admin/user ended with code: 403[0m
[04/Aug/2021 11:49:50,907] [31mUser: Anonymous User[0m
[04/Aug/2021 11:49:50,907] [31mRequest details:[0m
[04/Aug/2021 11:49:50,908] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '05285e4f-8ea6-4051-b0ff-2f0fc0e9294b', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=l8jjeu8z19hx1jfkjehn8wwiur4mgelw'}[0m
[04/Aug/2021 11:49:50,908] [31m{[0m
[04/Aug/2021 11:49:50,908] [31m    "email": "chpi@liis.su",[0m
[04/Aug/2021 11:49:50,908] [31m    "phone_number": "89118777872"[0m
[04/Aug/2021 11:49:50,909] [31m}[0m
[04/Aug/2021 11:49:50,909] [31m[0m
[04/Aug/2021 11:49:50,909] [31mResponse details:[0m
[04/Aug/2021 11:49:50,909] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Cookie, Origin'), 'allow': ('Allow', 'GET, POST, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '58')}[0m
[04/Aug/2021 11:49:50,910] [31m{"detail":"Authentication credentials were not provided."}[0m
[04/Aug/2021 11:49:50,910] [31mUsed tables: django_session[0m
[04/Aug/2021 11:49:51,627] [31m[0m
[04/Aug/2021 11:49:51,627] [31mRequest on POST /admin/user ended with code: 403[0m
[04/Aug/2021 11:49:51,627] [31mUser: Anonymous User[0m
[04/Aug/2021 11:49:51,628] [31mRequest details:[0m
[04/Aug/2021 11:49:51,628] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'd2508f31-d924-4414-837a-59230ed92f45', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=l8jjeu8z19hx1jfkjehn8wwiur4mgelw'}[0m
[04/Aug/2021 11:49:51,628] [31m{[0m
[04/Aug/2021 11:49:51,629] [31m    "email": "chpi@liis.su",[0m
[04/Aug/2021 11:49:51,629] [31m    "phone_number": "89118777872"[0m
[04/Aug/2021 11:49:51,629] [31m}[0m
[04/Aug/2021 11:49:51,629] [31m[0m
[04/Aug/2021 11:49:51,629] [31mResponse details:[0m
[04/Aug/2021 11:49:51,629] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Cookie, Origin'), 'allow': ('Allow', 'GET, POST, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '58')}[0m
[04/Aug/2021 11:49:51,630] [31m{"detail":"Authentication credentials were not provided."}[0m
[04/Aug/2021 11:49:51,630] [31mUsed tables: django_session[0m
[04/Aug/2021 12:07:16,118] [31m[0m
[04/Aug/2021 12:07:16,119] [31mRequest on GET /admin/user ended with code: 401[0m
[04/Aug/2021 12:07:16,119] [31mUser: Anonymous User[0m
[04/Aug/2021 12:07:16,119] [31mRequest details:[0m
[04/Aug/2021 12:07:16,120] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'a5927d1d-5996-4c49-862e-3c7e5065ff05', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[04/Aug/2021 12:07:16,120] [31mResponse details:[0m
[04/Aug/2021 12:07:16,120] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'www-authenticate': ('WWW-Authenticate', 'Bearer realm="api"'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '183')}[0m
[04/Aug/2021 12:07:16,120] [31m{"detail":"Given token not valid for any token type","code":"token_not_valid","messages":[{"token_class":"AccessToken","token_type":"access","message":"Token is invalid or expired"}]}[0m
[04/Aug/2021 12:07:19,523] [32m[0m
[04/Aug/2021 12:07:19,523] [32mRequest on POST /mobile/user/login ended with code: 200[0m
[04/Aug/2021 12:07:19,523] [32mUser: Anonymous User[0m
[04/Aug/2021 12:07:19,524] [32mUsed tables: users_user, django_session, users_account[0m
[04/Aug/2021 12:07:34,364] [32m[0m
[04/Aug/2021 12:07:34,364] [32mRequest on GET /admin/user ended with code: 200[0m
[04/Aug/2021 12:07:34,364] [32mUser: fe87620c-5e80-4a1c-9c30-c4681387483a, Account: 7689fea5-32e6-4b36-a353-e152e8eb814d[0m
[04/Aug/2021 12:07:34,365] [32mUsed tables: users_account_groups, users_officepanelrelation, files_file, users_account, groups_group, users_user[0m
[04/Aug/2021 12:29:00,028] [31m[0m
[04/Aug/2021 12:29:00,028] [31mRequest on GET /admin/user ended with code: 401[0m
[04/Aug/2021 12:29:00,028] [31mUser: Anonymous User[0m
[04/Aug/2021 12:29:00,028] [31mRequest details:[0m
[04/Aug/2021 12:29:00,029] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '70b8000a-c4ac-4102-97b5-e576f3564f59', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[04/Aug/2021 12:29:00,029] [31mResponse details:[0m
[04/Aug/2021 12:29:00,029] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'www-authenticate': ('WWW-Authenticate', 'Bearer realm="api"'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '51')}[0m
[04/Aug/2021 12:29:00,029] [31m{"detail":"User not found","code":"user_not_found"}[0m
[04/Aug/2021 12:29:00,030] [31mUsed tables: users_user[0m
[04/Aug/2021 12:29:05,853] [31m[0m
[04/Aug/2021 12:29:05,854] [31mRequest on POST /mobile/user/login ended with code: 400[0m
[04/Aug/2021 12:29:05,854] [31mUser: Anonymous User[0m
[04/Aug/2021 12:29:05,854] [31mRequest details:[0m
[04/Aug/2021 12:29:05,855] [31m{'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '73588f9e-e6ea-4cad-9fe5-021de9d06163', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[04/Aug/2021 12:29:05,856] [31mResponse details:[0m
[04/Aug/2021 12:29:05,857] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Cookie, Origin'), 'allow': ('Allow', 'POST, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '41')}[0m
[04/Aug/2021 12:29:05,857] [31m{"message":"Incorrect email or password"}[0m
[04/Aug/2021 12:29:05,857] [31mUsed tables: django_session, users_user[0m
[04/Aug/2021 12:29:09,668] [32m[0m
[04/Aug/2021 12:29:09,669] [32mRequest on POST /mobile/user/login ended with code: 200[0m
[04/Aug/2021 12:29:09,669] [32mUser: Anonymous User[0m
[04/Aug/2021 12:29:09,670] [32mUsed tables: django_session, users_account, users_user[0m
[04/Aug/2021 12:29:58,989] [32m[0m
[04/Aug/2021 12:29:58,989] [32mRequest on GET /admin/user ended with code: 200[0m
[04/Aug/2021 12:29:58,989] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[04/Aug/2021 12:29:58,989] [32mUsed tables: users_account, users_user, users_officepanelrelation, users_account_groups, files_file, groups_group[0m
[04/Aug/2021 12:30:06,702] [32m[0m
[04/Aug/2021 12:30:06,702] [32mRequest on GET /admin/booking ended with code: 200[0m
[04/Aug/2021 12:30:06,703] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[04/Aug/2021 12:30:06,704] [32mUsed tables: users_account, users_user, group_bookings_groupbooking, room_types_roomtype, rooms_room, users_account_groups, bookings_booking, floors_floor, groups_group, tables_table, offices_office[0m
[04/Aug/2021 12:30:16,725] [31m[0m
[04/Aug/2021 12:30:16,725] [31mRequest on POST /admin/booking ended with code: 400[0m
[04/Aug/2021 12:30:16,725] [31mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[04/Aug/2021 12:30:16,726] [31mRequest details:[0m
[04/Aug/2021 12:30:16,726] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '129cb23e-3fb9-4414-b30e-430eaa518f2c', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=9qgt0wtxh8d5nx7pkxpeuxpegff8v51v'}[0m
[04/Aug/2021 12:30:16,726] [31mResponse details:[0m
[04/Aug/2021 12:30:16,726] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '131')}[0m
[04/Aug/2021 12:30:16,726] [31m{"user_id":["This field is required."],"date_to":["This field is required."],"message":"This field is required.","code":"required"}[0m
[04/Aug/2021 12:30:16,727] [31mUsed tables: users_account, users_account_groups, groups_group, users_user[0m
[04/Aug/2021 12:30:51,273] [31m[0m
[04/Aug/2021 12:30:51,273] [31mRequest on POST /admin/booking ended with code: 400[0m
[04/Aug/2021 12:30:51,273] [31mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[04/Aug/2021 12:30:51,273] [31mRequest details:[0m
[04/Aug/2021 12:30:51,274] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'd898bf7c-3e70-4b6f-bd3e-c28ef95e51e8', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=9qgt0wtxh8d5nx7pkxpeuxpegff8v51v'}[0m
[04/Aug/2021 12:30:51,274] [31m{[0m
[04/Aug/2021 12:30:51,274] [31m    "user_id": "",[0m
[04/Aug/2021 12:30:51,274] [31m    "date_to": ""[0m
[04/Aug/2021 12:30:51,274] [31m}[0m
[04/Aug/2021 12:30:51,274] [31mResponse details:[0m
[04/Aug/2021 12:30:51,274] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '221')}[0m
[04/Aug/2021 12:30:51,274] [31m{"user_id":["This field may not be null."],"date_to":["Datetime has wrong format. Use one of these formats instead: YYYY-MM-DDThh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z]."],"message":"This field may not be null.","code":"null"}[0m
[04/Aug/2021 12:30:51,275] [31mUsed tables: users_account, users_account_groups, groups_group, users_user[0m
[04/Aug/2021 12:31:15,604] [31m[0m
[04/Aug/2021 12:31:15,605] [31mRequest on POST /admin/booking ended with code: 400[0m
[04/Aug/2021 12:31:15,605] [31mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[04/Aug/2021 12:31:15,605] [31mRequest details:[0m
[04/Aug/2021 12:31:15,605] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'c222457c-04fd-4209-a45f-a1359d2a0bc2', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=9qgt0wtxh8d5nx7pkxpeuxpegff8v51v'}[0m
[04/Aug/2021 12:31:15,605] [31m{[0m
[04/Aug/2021 12:31:15,605] [31m    "user_id": "",[0m
[04/Aug/2021 12:31:15,605] [31m    "date_to": "2021-08-04T15:30:00"[0m
[04/Aug/2021 12:31:15,606] [31m}[0m
[04/Aug/2021 12:31:15,606] [31mResponse details:[0m
[04/Aug/2021 12:31:15,606] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '97')}[0m
[04/Aug/2021 12:31:15,606] [31m{"user_id":["This field may not be null."],"message":"This field may not be null.","code":"null"}[0m
[04/Aug/2021 12:31:15,606] [31mUsed tables: users_account, users_account_groups, groups_group, users_user[0m
[04/Aug/2021 12:31:44,473] [31m[0m
[04/Aug/2021 12:31:44,473] [31mRequest on POST /admin/booking ended with code: 400[0m
[04/Aug/2021 12:31:44,473] [31mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[04/Aug/2021 12:31:44,473] [31mRequest details:[0m
[04/Aug/2021 12:31:44,474] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'b318eeab-b473-4fd9-925f-990c2e566c7d', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=9qgt0wtxh8d5nx7pkxpeuxpegff8v51v'}[0m
[04/Aug/2021 12:31:44,474] [31m{[0m
[04/Aug/2021 12:31:44,474] [31m    "user_id": "17aa3794-1b36-422f-b6b8-a04de827bc87",[0m
[04/Aug/2021 12:31:44,474] [31m    "date_to": "2021-08-04T15:30:00"[0m
[04/Aug/2021 12:31:44,474] [31m}[0m
[04/Aug/2021 12:31:44,474] [31mResponse details:[0m
[04/Aug/2021 12:31:44,475] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '33')}[0m
[04/Aug/2021 12:31:44,475] [31m{"message":"Table not specified"}[0m
[04/Aug/2021 12:31:44,475] [31mUsed tables: users_account, users_account_groups, groups_group, users_user[0m
[04/Aug/2021 12:32:03,344] [35;1m[35;1mInternal Server Error: /admin/booking[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/p7chkn/Dev/booking-api-django/bookings/serializers_admin.py", line 169, in create
    validated_data['date_from'],
KeyError: 'date_from'
[04/Aug/2021 12:32:03,349] [31m[0m
[04/Aug/2021 12:32:03,350] [31mRequest on POST /admin/booking ended with code: 500[0m
[04/Aug/2021 12:32:03,350] [31mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[04/Aug/2021 12:32:03,350] [31mRequest details:[0m
[04/Aug/2021 12:32:03,350] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '9f6c23e7-52ea-4f61-89b8-11a5e0773d5b', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=9qgt0wtxh8d5nx7pkxpeuxpegff8v51v'}[0m
[04/Aug/2021 12:32:03,350] [31m{[0m
[04/Aug/2021 12:32:03,351] [31m    "user_id": "17aa3794-1b36-422f-b6b8-a04de827bc87",[0m
[04/Aug/2021 12:32:03,351] [31m    "date_to": "2021-08-04T15:30:00",[0m
[04/Aug/2021 12:32:03,351] [31m    "table": "13a653d5-cd2d-4d7c-aab3-43a5974aa797"[0m
[04/Aug/2021 12:32:03,351] [31m}[0m
[04/Aug/2021 12:32:03,351] [31mResponse details:[0m
[04/Aug/2021 12:32:03,351] [31mUsed tables: users_account, users_user, room_types_roomtype, rooms_room, users_account_groups, groups_group, tables_table[0m
[04/Aug/2021 12:32:24,070] [35;1m[35;1mInternal Server Error: /admin/booking[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/p7chkn/Dev/booking-api-django/bookings/serializers_admin.py", line 176, in create
    return self.Meta.model.objects.create(
  File "/home/p7chkn/Dev/booking-api-django/bookings/models.py", line 101, in create
    obj.save(kwargs=language)
  File "/home/p7chkn/Dev/booking-api-django/bookings/models.py", line 181, in save
    if GLOBAL_DATE_FROM_WS[f'{self.table.id}'] == self.date_from.date():
KeyError: '13a653d5-cd2d-4d7c-aab3-43a5974aa797'
[04/Aug/2021 12:32:24,071] [31m[0m
[04/Aug/2021 12:32:24,071] [31mRequest on POST /admin/booking ended with code: 500[0m
[04/Aug/2021 12:32:24,071] [31mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[04/Aug/2021 12:32:24,071] [31mRequest details:[0m
[04/Aug/2021 12:32:24,071] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '08826bdf-cbca-4352-8c19-207843ca55c1', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=9qgt0wtxh8d5nx7pkxpeuxpegff8v51v'}[0m
[04/Aug/2021 12:32:24,071] [31m{[0m
[04/Aug/2021 12:32:24,072] [31m    "user_id": "17aa3794-1b36-422f-b6b8-a04de827bc87",[0m
[04/Aug/2021 12:32:24,072] [31m    "date_to": "2021-08-04T15:30:00",[0m
[04/Aug/2021 12:32:24,072] [31m    "date_from": "2021-08-04T15:00:00",[0m
[04/Aug/2021 12:32:24,072] [31m    "table": "13a653d5-cd2d-4d7c-aab3-43a5974aa797"[0m
[04/Aug/2021 12:32:24,072] [31m}[0m
[04/Aug/2021 12:32:24,073] [31mResponse details:[0m
[04/Aug/2021 12:32:24,073] [31mUsed tables: users_account, bookings_jobstore, users_user, room_types_roomtype, rooms_room, users_account_groups, bookings_booking, groups_group, tables_table[0m
[04/Aug/2021 13:40:23,388] [31m[0m
[04/Aug/2021 13:40:23,388] [31mRequest on POST /admin/booking ended with code: 401[0m
[04/Aug/2021 13:40:23,388] [31mUser: Anonymous User[0m
[04/Aug/2021 13:40:23,388] [31mRequest details:[0m
[04/Aug/2021 13:40:23,389] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '85d33b32-02e3-4a97-859e-192b396f9987', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[04/Aug/2021 13:40:23,389] [31m{[0m
[04/Aug/2021 13:40:23,389] [31m    "user_id": "17aa3794-1b36-422f-b6b8-a04de827bc87",[0m
[04/Aug/2021 13:40:23,389] [31m    "date_to": "2021-08-04T15:30:00",[0m
[04/Aug/2021 13:40:23,389] [31m    "date_from": "2021-08-04T15:00:00",[0m
[04/Aug/2021 13:40:23,389] [31m    "table": "13a653d5-cd2d-4d7c-aab3-43a5974aa797"[0m
[04/Aug/2021 13:40:23,389] [31m}[0m
[04/Aug/2021 13:40:23,390] [31mResponse details:[0m
[04/Aug/2021 13:40:23,390] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'www-authenticate': ('WWW-Authenticate', 'Bearer realm="api"'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '183')}[0m
[04/Aug/2021 13:40:23,390] [31m{"detail":"Given token not valid for any token type","code":"token_not_valid","messages":[{"token_class":"AccessToken","token_type":"access","message":"Token is invalid or expired"}]}[0m
[04/Aug/2021 13:40:27,580] [32m[0m
[04/Aug/2021 13:40:27,580] [32mRequest on POST /mobile/user/login ended with code: 200[0m
[04/Aug/2021 13:40:27,581] [32mUser: Anonymous User[0m
[04/Aug/2021 13:40:27,581] [32mUsed tables: users_account, users_user, django_session[0m
[04/Aug/2021 13:40:37,627] [35;1m[35;1mInternal Server Error: /admin/booking[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/p7chkn/Dev/booking-api-django/bookings/serializers_admin.py", line 176, in create
    return self.Meta.model.objects.create(
  File "/home/p7chkn/Dev/booking-api-django/bookings/models.py", line 97, in create
    obj.save(kwargs=language)
  File "/home/p7chkn/Dev/booking-api-django/bookings/models.py", line 177, in save
    if GLOBAL_DATE_FROM_WS[f'{self.table.id}'] == self.date_from.date():
KeyError: '13a653d5-cd2d-4d7c-aab3-43a5974aa797'
[04/Aug/2021 13:40:37,629] [31m[0m
[04/Aug/2021 13:40:37,629] [31mRequest on POST /admin/booking ended with code: 500[0m
[04/Aug/2021 13:40:37,629] [31mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[04/Aug/2021 13:40:37,630] [31mRequest details:[0m
[04/Aug/2021 13:40:37,630] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'fa4fb420-58dc-4595-8c4b-afac4554286a', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=g5faoipwockzhhhxn7kqccmh54hhtai3'}[0m
[04/Aug/2021 13:40:37,630] [31m{[0m
[04/Aug/2021 13:40:37,630] [31m    "user_id": "17aa3794-1b36-422f-b6b8-a04de827bc87",[0m
[04/Aug/2021 13:40:37,630] [31m    "date_to": "2021-08-04T15:30:00",[0m
[04/Aug/2021 13:40:37,630] [31m    "date_from": "2021-08-04T15:00:00",[0m
[04/Aug/2021 13:40:37,630] [31m    "table": "13a653d5-cd2d-4d7c-aab3-43a5974aa797"[0m
[04/Aug/2021 13:40:37,630] [31m}[0m
[04/Aug/2021 13:40:37,631] [31mResponse details:[0m
[04/Aug/2021 13:40:37,631] [31mUsed tables: users_account, users_account_groups, room_types_roomtype, tables_table, users_user, bookings_jobstore, bookings_booking, groups_group, rooms_room[0m
[04/Aug/2021 13:48:02,557] [35;1m[35;1mInternal Server Error: /admin/booking[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/p7chkn/Dev/booking-api-django/bookings/serializers_admin.py", line 176, in create
    return self.Meta.model.objects.create(
  File "/home/p7chkn/Dev/booking-api-django/bookings/models.py", line 97, in create
    obj.save(kwargs=language)
  File "/home/p7chkn/Dev/booking-api-django/bookings/models.py", line 177, in save
    if GLOBAL_DATE_FROM_WS[f'{self.table.id}'] == self.date_from.date():
KeyError: '13a653d5-cd2d-4d7c-aab3-43a5974aa797'
[04/Aug/2021 13:48:02,561] [31m[0m
[04/Aug/2021 13:48:02,561] [31mRequest on POST /admin/booking ended with code: 500[0m
[04/Aug/2021 13:48:02,561] [31mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[04/Aug/2021 13:48:02,562] [31mRequest details:[0m
[04/Aug/2021 13:48:02,562] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '8f17691a-6c3c-4b8e-b61e-6871648b3e29', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=g5faoipwockzhhhxn7kqccmh54hhtai3'}[0m
[04/Aug/2021 13:48:02,562] [31m{[0m
[04/Aug/2021 13:48:02,562] [31m    "user_id": "17aa3794-1b36-422f-b6b8-a04de827bc87",[0m
[04/Aug/2021 13:48:02,563] [31m    "date_to": "2021-08-04T15:30:00",[0m
[04/Aug/2021 13:48:02,563] [31m    "date_from": "2021-08-04T15:00:00",[0m
[04/Aug/2021 13:48:02,563] [31m    "table": "13a653d5-cd2d-4d7c-aab3-43a5974aa797"[0m
[04/Aug/2021 13:48:02,563] [31m}[0m
[04/Aug/2021 13:48:02,563] [31mResponse details:[0m
[04/Aug/2021 13:48:02,564] [31mUsed tables: users_user, groups_group, users_account_groups, room_types_roomtype, tables_table, users_account, bookings_booking, bookings_jobstore, rooms_room[0m
[04/Aug/2021 13:48:59,033] [35;1m[35;1mInternal Server Error: /admin/booking[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/p7chkn/Dev/booking-api-django/bookings/serializers_admin.py", line 176, in create
    return self.Meta.model.objects.create(
  File "/home/p7chkn/Dev/booking-api-django/bookings/models.py", line 97, in create
    obj.save(kwargs=language)
  File "/home/p7chkn/Dev/booking-api-django/bookings/models.py", line 178, in save
    if GLOBAL_DATE_FROM_WS[f'{self.table.id}'] == self.date_from.date():
KeyError: '13a653d5-cd2d-4d7c-aab3-43a5974aa797'
[04/Aug/2021 13:48:59,037] [31m[0m
[04/Aug/2021 13:48:59,038] [31mRequest on POST /admin/booking ended with code: 500[0m
[04/Aug/2021 13:48:59,038] [31mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[04/Aug/2021 13:48:59,038] [31mRequest details:[0m
[04/Aug/2021 13:48:59,039] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'c610f484-0aea-42d6-8b0e-919b9dff6b97', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=g5faoipwockzhhhxn7kqccmh54hhtai3'}[0m
[04/Aug/2021 13:48:59,039] [31m{[0m
[04/Aug/2021 13:48:59,039] [31m    "user_id": "17aa3794-1b36-422f-b6b8-a04de827bc87",[0m
[04/Aug/2021 13:48:59,039] [31m    "date_to": "2021-08-04T15:30:00",[0m
[04/Aug/2021 13:48:59,040] [31m    "date_from": "2021-08-04T15:00:00",[0m
[04/Aug/2021 13:48:59,040] [31m    "table": "13a653d5-cd2d-4d7c-aab3-43a5974aa797"[0m
[04/Aug/2021 13:48:59,040] [31m}[0m
[04/Aug/2021 13:48:59,040] [31mResponse details:[0m
[04/Aug/2021 13:48:59,042] [31mUsed tables: bookings_booking, bookings_jobstore, users_account_groups, users_account, room_types_roomtype, tables_table, rooms_room, groups_group, users_user[0m
[04/Aug/2021 13:51:02,231] [32m[0m
[04/Aug/2021 13:51:02,231] [32mRequest on POST /admin/booking ended with code: 201[0m
[04/Aug/2021 13:51:02,231] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[04/Aug/2021 13:51:02,231] [32mUsed tables: bookings_booking, bookings_jobstore, users_account_groups, users_account, offices_office, room_types_roomtype, users_officepanelrelation, tables_table, rooms_room, groups_group, floors_floor, users_user[0m
[04/Aug/2021 14:07:40,462] [32m[0m
[04/Aug/2021 14:07:40,462] [32mRequest on POST /admin/booking ended with code: 201[0m
[04/Aug/2021 14:07:40,463] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[04/Aug/2021 14:07:40,465] [32mUsed tables: users_officepanelrelation, rooms_room, users_account_groups, groups_group, room_types_roomtype, bookings_booking, bookings_jobstore, offices_office, tables_table, users_user, floors_floor, users_account[0m
[04/Aug/2021 14:15:10,482] [32m[0m
[04/Aug/2021 14:15:10,482] [32mRequest on DELETE /admin/booking/af7e15fb-b673-4038-9ae8-27137194aa3f ended with code: 204[0m
[04/Aug/2021 14:15:10,483] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[04/Aug/2021 14:15:10,484] [32mUsed tables: bookings_booking, bookings_jobstore, users_officepanelrelation, users_account_groups, tables_table, groups_group, files_file, tables_table_images, group_bookings_groupbooking, users_account, rooms_room, users_user, room_types_roomtype[0m
[05/Aug/2021 07:16:56,496] connected
[05/Aug/2021 07:16:58,418] connected
[05/Aug/2021 07:18:03,035] Web socket connected
[05/Aug/2021 07:18:03,884] Web socket disconnected
[05/Aug/2021 07:18:04,842] Web socket connected
[05/Aug/2021 07:18:05,539] Web socket disconnected
[05/Aug/2021 07:23:46,609] Web socket connected
[05/Aug/2021 07:25:04,541] Web socket connected
[05/Aug/2021 07:25:44,039] Web socket connected
[05/Aug/2021 07:26:57,417] Web socket connected
[05/Aug/2021 07:28:40,051] Web socket connected
[05/Aug/2021 08:24:30,393] Web socket connected
[05/Aug/2021 08:24:55,405] [31m[0m
[05/Aug/2021 08:24:55,405] [31mRequest on POST /admin/booking ended with code: 401[0m
[05/Aug/2021 08:24:55,406] [31mUser: Anonymous User[0m
[05/Aug/2021 08:24:55,406] [31mRequest details:[0m
[05/Aug/2021 08:24:55,407] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '65760bf6-c97c-48e1-93a8-6e17e7865496', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[05/Aug/2021 08:24:55,407] [31m{[0m
[05/Aug/2021 08:24:55,407] [31m    "user_id": "17aa3794-1b36-422f-b6b8-a04de827bc87",[0m
[05/Aug/2021 08:24:55,407] [31m    "date_to": "2021-08-05T15:30:00",[0m
[05/Aug/2021 08:24:55,407] [31m    "date_from": "2021-08-05T15:00:00",[0m
[05/Aug/2021 08:24:55,407] [31m    "table": "13a653d5-cd2d-4d7c-aab3-43a5974aa797"[0m
[05/Aug/2021 08:24:55,408] [31m}[0m
[05/Aug/2021 08:24:55,408] [31mResponse details:[0m
[05/Aug/2021 08:24:55,409] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'www-authenticate': ('WWW-Authenticate', 'Bearer realm="api"'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '183')}[0m
[05/Aug/2021 08:24:55,409] [31m{"detail":"Given token not valid for any token type","code":"token_not_valid","messages":[{"token_class":"AccessToken","token_type":"access","message":"Token is invalid or expired"}]}[0m
[05/Aug/2021 08:24:59,176] [32m[0m
[05/Aug/2021 08:24:59,177] [32mRequest on POST /mobile/user/login ended with code: 200[0m
[05/Aug/2021 08:24:59,177] [32mUser: Anonymous User[0m
[05/Aug/2021 08:24:59,179] [32mUsed tables: users_user, django_session, users_account[0m
[05/Aug/2021 08:25:28,345] [32m[0m
[05/Aug/2021 08:25:28,345] [32mRequest on POST /admin/booking ended with code: 201[0m
[05/Aug/2021 08:25:28,345] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[05/Aug/2021 08:25:28,346] [32mUsed tables: offices_office, users_account_groups, room_types_roomtype, users_officepanelrelation, bookings_jobstore, groups_group, bookings_booking, tables_table, users_user, floors_floor, rooms_room, users_account[0m
[05/Aug/2021 10:03:46,123] [31m[0m
[05/Aug/2021 10:03:46,123] [31mRequest on POST /admin/booking ended with code: 401[0m
[05/Aug/2021 10:03:46,123] [31mUser: Anonymous User[0m
[05/Aug/2021 10:03:46,123] [31mRequest details:[0m
[05/Aug/2021 10:03:46,124] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '03eef7a0-d9d9-4100-95e6-fa949ae06c36', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[05/Aug/2021 10:03:46,124] [31m{[0m
[05/Aug/2021 10:03:46,124] [31m    "user_id": "17aa3794-1b36-422f-b6b8-a04de827bc87",[0m
[05/Aug/2021 10:03:46,124] [31m    "date_to": "2021-08-05T15:30:00",[0m
[05/Aug/2021 10:03:46,124] [31m    "date_from": "2021-08-05T15:00:00",[0m
[05/Aug/2021 10:03:46,124] [31m    "table": "13a653d5-cd2d-4d7c-aab3-43a5974aa797"[0m
[05/Aug/2021 10:03:46,124] [31m}[0m
[05/Aug/2021 10:03:46,124] [31mResponse details:[0m
[05/Aug/2021 10:03:46,125] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'www-authenticate': ('WWW-Authenticate', 'Bearer realm="api"'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '183')}[0m
[05/Aug/2021 10:03:46,125] [31m{"detail":"Given token not valid for any token type","code":"token_not_valid","messages":[{"token_class":"AccessToken","token_type":"access","message":"Token is invalid or expired"}]}[0m
[05/Aug/2021 10:03:49,717] [32m[0m
[05/Aug/2021 10:03:49,717] [32mRequest on POST /mobile/user/login ended with code: 200[0m
[05/Aug/2021 10:03:49,717] [32mUser: Anonymous User[0m
[05/Aug/2021 10:03:49,718] [32mUsed tables: users_user, django_session, users_account[0m
[05/Aug/2021 10:04:06,343] [35;1m[35;1mInternal Server Error: /admin/booking[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/p7chkn/Dev/booking-api-django/bookings/serializers_admin.py", line 176, in create
    return self.Meta.model.objects.create(
  File "/home/p7chkn/Dev/booking-api-django/bookings/models.py", line 99, in create
    obj.save(kwargs=language)
  File "/home/p7chkn/Dev/booking-api-django/bookings/models.py", line 187, in save
    if dict_for_wc['global_date_from_ws'][f'{self.table.id}'] == self.date_from.date():
KeyError: '13a653d5-cd2d-4d7c-aab3-43a5974aa797'
[05/Aug/2021 10:04:06,352] [31m[0m
[05/Aug/2021 10:04:06,353] [31mRequest on POST /admin/booking ended with code: 500[0m
[05/Aug/2021 10:04:06,353] [31mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[05/Aug/2021 10:04:06,353] [31mRequest details:[0m
[05/Aug/2021 10:04:06,354] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'dfe10e5f-6bdc-4bfe-882a-2401746cad1f', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_COOKIE': 'sessionid=1kyxcl8gmr6x2ff6zpq87fdldk6l8aig'}[0m
[05/Aug/2021 10:04:06,354] [31m{[0m
[05/Aug/2021 10:04:06,354] [31m    "user_id": "17aa3794-1b36-422f-b6b8-a04de827bc87",[0m
[05/Aug/2021 10:04:06,355] [31m    "date_to": "2021-08-05T15:30:00",[0m
[05/Aug/2021 10:04:06,355] [31m    "date_from": "2021-08-05T15:00:00",[0m
[05/Aug/2021 10:04:06,355] [31m    "table": "13a653d5-cd2d-4d7c-aab3-43a5974aa797"[0m
[05/Aug/2021 10:04:06,355] [31m}[0m
[05/Aug/2021 10:04:06,356] [31mResponse details:[0m
[05/Aug/2021 10:04:06,356] [31mUsed tables: room_types_roomtype, groups_group, rooms_room, tables_table, bookings_jobstore, users_officepanelrelation, bookings_booking, users_account, users_user, users_account_groups[0m
[05/Aug/2021 10:04:22,163] Web socket connected
[05/Aug/2021 10:04:26,858] [32m[0m
[05/Aug/2021 10:04:26,858] [32mRequest on POST /admin/booking ended with code: 201[0m
[05/Aug/2021 10:04:26,858] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[05/Aug/2021 10:04:26,860] [32mUsed tables: room_types_roomtype, groups_group, rooms_room, floors_floor, tables_table, bookings_jobstore, users_officepanelrelation, bookings_booking, users_account, users_user, offices_office, users_account_groups[0m
[05/Aug/2021 10:16:14,655] Web socket connected
[05/Aug/2021 10:20:36,188] Web socket connected
[05/Aug/2021 10:24:40,544] [32m[0m
[05/Aug/2021 10:24:40,544] [32mRequest on POST /admin/booking ended with code: 201[0m
[05/Aug/2021 10:24:40,544] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[05/Aug/2021 10:24:40,546] [32mUsed tables: floors_floor, users_officepanelrelation, users_account, groups_group, room_types_roomtype, offices_office, users_user, rooms_room, bookings_jobstore, users_account_groups, bookings_booking, tables_table[0m
[05/Aug/2021 10:24:48,463] Web socket connected
[05/Aug/2021 10:25:26,752] [32m[0m
[05/Aug/2021 10:25:26,752] [32mRequest on POST /admin/booking ended with code: 201[0m
[05/Aug/2021 10:25:26,752] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[05/Aug/2021 10:25:26,753] [32mUsed tables: floors_floor, users_officepanelrelation, users_account, groups_group, room_types_roomtype, offices_office, users_user, rooms_room, bookings_jobstore, users_account_groups, bookings_booking, tables_table[0m
[05/Aug/2021 10:26:15,037] Web socket connected
[05/Aug/2021 10:27:32,448] Web socket connected
[05/Aug/2021 10:28:15,724] [32m[0m
[05/Aug/2021 10:28:15,724] [32mRequest on POST /admin/booking ended with code: 201[0m
[05/Aug/2021 10:28:15,724] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[05/Aug/2021 10:28:15,726] [32mUsed tables: groups_group, room_types_roomtype, users_account, users_officepanelrelation, tables_table, bookings_booking, floors_floor, offices_office, users_account_groups, bookings_jobstore, users_user, rooms_room[0m
[05/Aug/2021 10:29:18,137] Web socket connected
[05/Aug/2021 10:29:44,399] [32m[0m
[05/Aug/2021 10:29:44,399] [32mRequest on POST /admin/booking ended with code: 201[0m
[05/Aug/2021 10:29:44,399] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[05/Aug/2021 10:29:44,402] [32mUsed tables: bookings_jobstore, users_officepanelrelation, offices_office, groups_group, users_account_groups, rooms_room, bookings_booking, room_types_roomtype, users_user, tables_table, floors_floor, users_account[0m
[05/Aug/2021 10:30:52,315] Web socket connected
[05/Aug/2021 10:30:59,929] [32m[0m
[05/Aug/2021 10:30:59,929] [32mRequest on POST /admin/booking ended with code: 201[0m
[05/Aug/2021 10:30:59,930] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[05/Aug/2021 10:30:59,930] [32mUsed tables: rooms_room, offices_office, room_types_roomtype, users_account, tables_table, users_user, users_account_groups, bookings_booking, users_officepanelrelation, bookings_jobstore, groups_group, floors_floor[0m
[05/Aug/2021 10:32:14,589] [32m[0m
[05/Aug/2021 10:32:14,590] [32mRequest on POST /admin/booking ended with code: 201[0m
[05/Aug/2021 10:32:14,590] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[05/Aug/2021 10:32:14,591] [32mUsed tables: rooms_room, offices_office, room_types_roomtype, users_account, tables_table, users_user, users_account_groups, bookings_booking, users_officepanelrelation, bookings_jobstore, groups_group, floors_floor[0m
[05/Aug/2021 10:33:06,054] [32m[0m
[05/Aug/2021 10:33:06,055] [32mRequest on POST /admin/booking ended with code: 201[0m
[05/Aug/2021 10:33:06,055] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[05/Aug/2021 10:33:06,056] [32mUsed tables: rooms_room, offices_office, room_types_roomtype, users_account, tables_table, users_user, users_account_groups, bookings_booking, users_officepanelrelation, bookings_jobstore, groups_group, floors_floor[0m
[05/Aug/2021 10:38:30,892] [32m[0m
[05/Aug/2021 10:38:30,893] [32mRequest on POST /admin/booking ended with code: 201[0m
[05/Aug/2021 10:38:30,893] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[05/Aug/2021 10:38:30,894] [32mUsed tables: users_account_groups, rooms_room, tables_table, users_user, groups_group, bookings_booking, floors_floor, users_account, room_types_roomtype, bookings_jobstore, offices_office, users_officepanelrelation[0m
[05/Aug/2021 10:39:03,156] Web socket connected
[05/Aug/2021 10:39:12,776] [32m[0m
[05/Aug/2021 10:39:12,776] [32mRequest on POST /admin/booking ended with code: 201[0m
[05/Aug/2021 10:39:12,776] [32mUser: b61b0c6e-ee5b-4455-93ed-85133da4d9b6, Account: 097504bf-29ca-42a6-8b61-b6fa19772734[0m
[05/Aug/2021 10:39:12,777] [32mUsed tables: users_account_groups, rooms_room, tables_table, users_user, groups_group, bookings_booking, floors_floor, users_account, room_types_roomtype, bookings_jobstore, offices_office, users_officepanelrelation[0m
